//
// InfoReleaseDetailDtoOutput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InfoReleaseDetailDtoOutput: Codable {

    /** 工作要求 - 门槛 */
    public var require: PartInfoRequire
    /** 招聘信息 */
    public var partInfo: PartInfoDtoOutput
    /** 招聘信息对应门店 */
    public var store: Store
    /** 门店照片 */
    public var storeImages: [String]
    /** 自定义照片 */
    public var customImages: [String]
    /** 该招聘岗位的 特点 */
    public var features: [String]
    /** 工作时间 */
    public var workTimes: [Date]
    /** 已经报名的学生ids */
    public var cuserIds: [String]

    public init(require: PartInfoRequire, partInfo: PartInfoDtoOutput, store: Store, storeImages: [String], customImages: [String], features: [String], workTimes: [Date], cuserIds: [String]) {
        self.require = require
        self.partInfo = partInfo
        self.store = store
        self.storeImages = storeImages
        self.customImages = customImages
        self.features = features
        self.workTimes = workTimes
        self.cuserIds = cuserIds
    }


}

