//
// PartInfoDtoOutput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PartInfoDtoOutput: Codable {

    public enum SalaryTypeValue: Int, Codable { 
        case _0 = 0
        case _1 = 1
    }
    public enum BalanceTypeValue: Int, Codable { 
        case _0 = 0
        case _1 = 1
        case _2 = 2
    }
    public enum PayMethodValue: Int, Codable { 
        case _0 = 0
        case _1 = 1
    }
    public var _id: Int
    /** 发布用户Id */
    public var userId: String
    /** 门店Id */
    public var storeId: Int
    /** 薪资 */
    public var salary: Double
    /** 薪资类型 时薪、日薪、月薪 */
    public var salaryTypeValue: SalaryTypeValue
    /** 结算方式 日结、周结、月结等 */
    public var balanceTypeValue: BalanceTypeValue
    /** 工资方法方式 平台代发、线下自己结算 */
    public var payMethodValue: PayMethodValue
    /** 薪资类型 元/小时 元/天 */
    public var salaryType: String
    /** 结算方式 日结、周结、月结等 */
    public var balanceType: String
    /** 工资方法方式 平台代发、线下自己结算 */
    public var payMethod: String
    /** 要求人数 */
    public var recruitingNumbers: Int
    /** 标题 */
    public var title: String
    /** 职业Id */
    public var occupationId: Int
    /** 职业名称 */
    public var occupationName: String
    /** 发布公司 */
    public var companyName: String
    /** 工作行业 */
    public var jobIndustry: Int
    /** 工作内容 */
    public var jobContent: String
    /** 补充信息 */
    public var jobAsk: String?
    /** 要上几天班 */
    public var rTimeCount: Int
    /** 第一天班 yyyy-MM-dd */
    public var startDay: String
    /** 最后一天班(自动下架时间)  yyyy-MM-dd */
    public var endDay: String
    /** 上班时间 */
    public var startTime: String
    /** 下班时间 */
    public var endTime: String
    /** 午休时间 单位分钟 */
    public var restTime: Int
    /** 信息发布时间 */
    public var releaseDate: Date
    /** 信息发布时间 */
    public var releaseDateText: String
    /** 信息修改时间 */
    public var editDate: Date
    /** 发布在哪个城市 */
    public var releaseCityId: Int
    /** 审核状态 是否通过了审核 */
    public var isAuditSuccess: Bool
    /** 是否自定义图片 */
    public var isCustomImage: Bool
    /** 是否过期 true过期，false没过期 */
    public var isExpired: Bool
    /** 是否是红包工作 */
    public var isRad: Bool

    public init(_id: Int, userId: String, storeId: Int, salary: Double, salaryTypeValue: SalaryTypeValue, balanceTypeValue: BalanceTypeValue, payMethodValue: PayMethodValue, salaryType: String, balanceType: String, payMethod: String, recruitingNumbers: Int, title: String, occupationId: Int, occupationName: String, companyName: String, jobIndustry: Int, jobContent: String, jobAsk: String?, rTimeCount: Int, startDay: String, endDay: String, startTime: String, endTime: String, restTime: Int, releaseDate: Date, releaseDateText: String, editDate: Date, releaseCityId: Int, isAuditSuccess: Bool, isCustomImage: Bool, isExpired: Bool, isRad: Bool) {
        self._id = _id
        self.userId = userId
        self.storeId = storeId
        self.salary = salary
        self.salaryTypeValue = salaryTypeValue
        self.balanceTypeValue = balanceTypeValue
        self.payMethodValue = payMethodValue
        self.salaryType = salaryType
        self.balanceType = balanceType
        self.payMethod = payMethod
        self.recruitingNumbers = recruitingNumbers
        self.title = title
        self.occupationId = occupationId
        self.occupationName = occupationName
        self.companyName = companyName
        self.jobIndustry = jobIndustry
        self.jobContent = jobContent
        self.jobAsk = jobAsk
        self.rTimeCount = rTimeCount
        self.startDay = startDay
        self.endDay = endDay
        self.startTime = startTime
        self.endTime = endTime
        self.restTime = restTime
        self.releaseDate = releaseDate
        self.releaseDateText = releaseDateText
        self.editDate = editDate
        self.releaseCityId = releaseCityId
        self.isAuditSuccess = isAuditSuccess
        self.isCustomImage = isCustomImage
        self.isExpired = isExpired
        self.isRad = isRad
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId
        case storeId
        case salary
        case salaryTypeValue
        case balanceTypeValue
        case payMethodValue
        case salaryType
        case balanceType
        case payMethod
        case recruitingNumbers
        case title
        case occupationId
        case occupationName
        case companyName
        case jobIndustry
        case jobContent
        case jobAsk
        case rTimeCount
        case startDay
        case endDay
        case startTime
        case endTime
        case restTime
        case releaseDate
        case releaseDateText
        case editDate
        case releaseCityId
        case isAuditSuccess
        case isCustomImage
        case isExpired
        case isRad
    }


}

