//
// PartInfoRequire.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 兼职 - 工作要求(门槛) 一对一 关系 */

public struct PartInfoRequire: Codable {

    public enum RequireGender: Int, Codable { 
        case _0 = 0
        case _1 = 1
        case _2 = 2
    }
    public enum RequireExp: Int, Codable { 
        case _0 = 0
        case _1 = 1
        case _2 = 2
        case _3 = 3
    }
    public enum RequireEdu: Int, Codable { 
        case _0 = 0
        case _1 = 1
        case _2 = 2
        case _3 = 3
    }
    /** 最小年龄 */
    public var minAge: Int?
    /** 最大年龄 */
    public var maxAge: Int?
    /** 性别要求 */
    public var requireGender: RequireGender
    /** 经验要求 */
    public var requireExp: RequireExp
    /** 学历要求 */
    public var requireEdu: RequireEdu
    /** 简历投递要求 - 工作经验不为空，不满足条件的简历将无法投递 */
    public var mustExperienceNotEmpty: Bool
    public var mustEducationNotEmpty: Bool
    /** 年龄要求 */
    public var requireAgeText: String
    /** 性别要求 */
    public var requireGenderText: String
    /** 经验要求 */
    public var requireExpText: String
    /** 学历要求 */
    public var requireEduText: String

    public init(minAge: Int?, maxAge: Int?, requireGender: RequireGender, requireExp: RequireExp, requireEdu: RequireEdu, mustExperienceNotEmpty: Bool, mustEducationNotEmpty: Bool, requireAgeText: String, requireGenderText: String, requireExpText: String, requireEduText: String) {
        self.minAge = minAge
        self.maxAge = maxAge
        self.requireGender = requireGender
        self.requireExp = requireExp
        self.requireEdu = requireEdu
        self.mustExperienceNotEmpty = mustExperienceNotEmpty
        self.mustEducationNotEmpty = mustEducationNotEmpty
        self.requireAgeText = requireAgeText
        self.requireGenderText = requireGenderText
        self.requireExpText = requireExpText
        self.requireEduText = requireEduText
    }


}

