//
// Store.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 门店表 */

public struct Store: Codable {

    public var _id: Int
    /** 用户Id */
    public var userId: String
    /** 门店名 */
    public var storeName: String
    /** 店全名 */
    public var fullName: String
    /** 门店地址 */
    public var address: String
    /** 地址补充 */
    public var addressPlement: String?
    /** 门店Latitude */
    public var latitude: Double
    /** 门店Longitude */
    public var longitude: Double
    /** 门店HR手机号 */
    public var hrTel: String
    /** 门店HR姓名 */
    public var hrName: String

    public init(_id: Int, userId: String, storeName: String, fullName: String, address: String, addressPlement: String?, latitude: Double, longitude: Double, hrTel: String, hrName: String) {
        self._id = _id
        self.userId = userId
        self.storeName = storeName
        self.fullName = fullName
        self.address = address
        self.addressPlement = addressPlement
        self.latitude = latitude
        self.longitude = longitude
        self.hrTel = hrTel
        self.hrName = hrName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId
        case storeName
        case fullName
        case address
        case addressPlement
        case latitude
        case longitude
        case hrTel
        case hrName
    }


}

